blacklist btmrvl_sdio
blacklist btmrvl
blacklist bluetooth
blacklist mwifiex_sdio
blacklist mwifiex

alias sdio:c*v02DFd914D* jody-w3-sdio
options jody-w3-sdio fw_name=nxp/sdiouart9098_combo_v1.bin
options jody-w3-sdio cal_data_cfg=none
options jody-w3-sdio cfg80211_wext=0xf
options jody-w3-sdio drv_mode=3
options jody-w3-sdio dev_cap_mask=0xffffdbff
install jody-w3-sdio \
        /sbin/modprobe -i mlan; \
        /sbin/modprobe -i moal $CMDLINE_OPTS
remove jody-w3-sdio \
        /sbin/rmmod moal mlan

